version: "3.8"
services:
  qotd-service:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: qotd-service:latest # named image
    volumes: # expose underlying file changes to container for hot reloading 
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  db:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  redis-data:
